config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  root 'dashboard#home'

  resources :customers
  resources :users
  resources :emails, except: [:edit, :update, :destroy]
  resources :offers, except: [:index, :show]
  resources :offer_files, only: :destroy
  resources :recruitment_centers, except: :show
  resources :countries, except: :show
  resources :regions, except: :show
  resources :request_categories, except: :show
  resources :requests, except: [:show, :index]
  resources :customer_statuses, except: :show
end

app/controllers/customer_statuses_controller.rb
class CustomerStatusesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer_status, only: [:edit, :update, :destroy]

  def index
    @customer_statuses = CustomerStatus.filter_by(params[:filter]).page(params[:page])
  end

  def new
    @customer_status = CustomerStatus.new
  end

  def create
    @customer_status = CustomerStatus.new customer_status_params
    return redirect_to customer_statuses_path, notice: t('resources.create.success') if @customer_status.save
    render :new
  end

  def edit
  end

  def update
    success = @customer_status.update_attributes customer_status_params
    return redirect_to customer_statuses_path, notice: t('resources.update.success') if success
    render :edit
  end

  def destroy
    @customer_status.destroy
    redirect_to customer_statuses_path, notice: t('resources.destroy.success')
  end

  private

  def set_customer_status
    @customer_status = CustomerStatus.find params[:id]
  end

  def customer_status_params
    params.require(:customer_status).permit :name, :color
  end
end

app/views/customer_statuses/_form.html.haml
= bootstrap_nested_form_for @customer_status, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-5' do |f|
  = f.alert_message t 'views.forms.alert_message'

  = f.text_field :name
  = f.color_field :color

  = f.form_group do
    = f.submit t('resources.save'), class: 'btn btn-primary'

app/views/customer_statuses/edit.html.haml
- @page_title = t 'customer_status.edit.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'plus', t('resources.new'), new_customer_status_path, class: 'btn btn-default btn-sm'
      = icon_link_to 'list', t('resources.list'), customer_statuses_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'

app/views/customer_statuses/index.html.haml
- @page_title = t 'customer_status.index.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'plus', t('resources.new'), new_customer_status_path, class: 'btn btn-primary btn-sm'

  .box-body
    = search_form CustomerStatus, {name: {}}

    %small.pull-right.text-muted
      = t 'resources.count', count: number_with_delimiter(@customer_statuses.total_count)
      \|
      = t 'resources.pages', count: number_with_delimiter(@customer_statuses.total_pages)
    = paginate @customer_statuses

    %table.table.table-hover
      %thead
        %tr
          %th= t('activerecord.attributes.customer_status.name')
          %th= t('activerecord.attributes.customer_status.color')
          %th

      %tbody.rowlink
        - if @customer_statuses.total_count == 0
          %tr
            %td{colspan: 3}= t 'resources.no_items'
        - @customer_statuses.each do |status|
          - style = status.color ? "background-color: #{status.color}" : ''
          %tr
            %td= status.name
            %td{style: style}

            %td.rowlink-skip.text-right
              = icon_link_to 'edit', t('resources.edit'), edit_customer_status_path(status), class: 'btn btn-default btn-xs'
              = icon_link_to 'times', t('resources.delete'), status, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'

    %br

app/views/customer_statuses/new.html.haml
- @page_title = t 'customer_status.new.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'list', t('resources.list'), customer_statuses_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'