config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  root 'dashboard#home'

  resources :customers
  resources :users
  resources :emails, except: [:edit, :update, :destroy]
  resources :offers, except: [:index, :show]
  resources :offer_files, only: :destroy
  resources :recruitment_centers, except: :show
  resources :countries, except: :show
  resources :regions, except: :show
  resources :request_categories, except: :show
  resources :requests, except: [:show, :index]
  resources :customer_statuses, except: :show
end

app/models/user.rb
class User < ApplicationRecord
  include Filterable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  validates :email, format: Devise.email_regexp, presence: true, uniqueness: true

  default_scope -> () { order id: :asc }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.filter_by(params[:filter]).page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    success = user_params[:password].empty? ? @user.update_without_password(user_params) : @user.update(user_params)

    return redirect_to @user, notice: t('resources.update.success') if success
    render :edit
  end

  def new
    @user = User.new
  end

  def create
    user_data = user_params

    if user_data[:password].empty?
      user_data.delete :password
      user_data.delete :password_confirmation
    end

    @user = User.new(user_data)

    return redirect_to @user, notice: t('resources.created_at') if @user.save
    render :new
  end

  private

  def set_user
    @user = User.find params[:id]
  end
  
  def user_params
    params.require(:user).permit :email, :password, :password_confirmation, :current_password
  end
end

app/views/users/_form.html.haml
= bootstrap_nested_form_for @user, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-5' do |f|
  = f.alert_message t 'views.forms.alert_message'

  = f.text_field :email
  = f.password_field :password
  = f.password_field :password_confirmation

  = f.form_group do
    = f.submit t('resources.save'), class: 'btn btn-primary'

app/views/users/edit.html.haml
- @page_title = t 'user.edit.title'

.box
  .box-header
    %h3.box-title
    .box-tools
      = icon_link_to 'info-circle',t('resources.show'), @user, class: 'btn btn-primary btn-sm'
      = icon_link_to 'plus', t('resources.new'), new_user_path, class: 'btn btn-default btn-sm'
      = icon_link_to 'list', t('resources.list'), users_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'

app/views/users/index.html.haml
- @page_title = t 'user.index.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'plus', t('resources.new'), new_user_path, class: 'btn btn-primary btn-sm'

  .box-body
    = search_form User, email: {}

    %small.pull-right.text-muted
      = t 'resources.count', count: number_with_delimiter(@users.total_count)
      \|
      = t 'resources.pages', count: number_with_delimiter(@users.total_pages)
    = paginate @users

    %table.table.table-hover.table-sortable
      %thead
        %tr
          %th= t('activerecord.attributes.user.email')
          %th

      %tbody.rowlink
        - if @users.total_count == 0
          %tr
            %td{colspan: 2}= t 'resources.no_items'
        - @users.each do |user|
          %tr
            %td= link_to user.email, user

            %td.rowlink-skip.text-right
              = icon_link_to 'edit', t('resources.edit'), edit_user_path(user), class: 'btn btn-default btn-xs' if current_user == user
              = icon_link_to 'times', t('resources.delete'), user, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'

    %br

app/views/users/new.html.haml
- @page_title = t 'customer.new.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'list', t('resources.list'), customers_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'

app/views/users/show.html.haml
- @page_title = t 'user.show.title'

.row
  .col-xs-12
    .box.box-primary
      .box-header.with-border
        %h3.box-title= t('resources.details')
        .box-tools
          = icon_link_to 'edit', t('resources.edit'), edit_user_path, class: 'btn btn-primary btn-sm'
          = icon_link_to 'plus', t('resources.new'), new_user_path, class: 'btn btn-default btn-sm'
          = icon_link_to 'list', t('resources.list'), users_path, class: 'btn btn-default btn-sm'

      .box-body
        %dl.dl-horizontal.dl-details
          %dt= t('activerecord.attributes.user.email')
          %dd= @user.email

          %dt= t 'resources.created_at'
          %dd= @user.created_at