config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  root 'dashboard#home'

  resources :customers
  resources :users
  resources :emails, except: [:edit, :update, :destroy]
  resources :offers, except: [:index, :show]
  resources :offer_files, only: :destroy
  resources :recruitment_centers, except: :show
  resources :countries, except: :show
  resources :regions, except: :show
  resources :request_categories, except: :show
  resources :requests, except: [:show, :index]
  resources :customer_statuses, except: :show
end

app/models/customer.rb
class Customer < ApplicationRecord
  include Filterable

  belongs_to :recruitment_center, optional: true
  belongs_to :country, optional: true
  belongs_to :region, optional: true
  belongs_to :customer_status, optional: true

  has_many :requests, inverse_of: :customer, dependent: :destroy

  accepts_nested_attributes_for :requests

  validates_format_of :email, :with => Devise::email_regexp
  validates_presence_of :email
  validates_uniqueness_of :email

  def offers
    self.requests.map { |request| request.offer }
  end

  def contact_date
    self.offers.compact.select{ |offer| offer.contact_date >= Date.current }.sort_by(&:contact_date).first&.contact_date
  end

  def unresolved_requests?
    @unresolved = self.requests.any? { |request| request.offer.nil? } if @unresolved.nil?
    @unresolved
  end

  def self.filter_by_has_unresolved_request(scope, value)
    if Utility.yes? value
      scope.left_joins(requests: :offer).group('customers.id').having('COUNT(requests.*) > COUNT(offers.*)')
    else
      scope.left_joins(requests: :offer).group('customers.id').having('COUNT(requests.*) = COUNT(offers.*)')
    end
  end

  def self.filter_by_contact_date_from(scope, value)
    scope.left_joins(requests: :offer).where('offers.contact_date >= ?', Date.parse(value)).distinct
  end

  def self.filter_by_contact_date_to(scope, value)
    scope.left_joins(requests: :offer).where('offers.contact_date <= ?', Date.parse(value)).distinct
  end

  def self.filter_by_request_date_from(scope, value)
    scope.left_joins(:requests).where('requests.date >= ?', Date.parse(value)).distinct
  end

  def self.filter_by_request_date_to(scope, value)
    scope.left_joins(:requests).where('requests.date <= ?', Date.parse(value)).distinct
  end

  def self.filter_by_offer_date_from(scope, value)
    scope.left_joins(requests: :offer).where('offers.date >= ?', Date.parse(value)).distinct
  end

  def self.filter_by_offer_date_to(scope, value)
    scope.left_joins(requests: :offer).where('offers.date <= ?', Date.parse(value)).distinct
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:edit, :update, :destroy]

  def index
    @customers = Customer.includes(:recruitment_center, :region, :requests).filter_by(params[:filter]).page params[:page]
  end

  def show
    @customer = Customer.includes(:recruitment_center, :country, :region, requests: :offer).find params[:id]
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new customer_params
    return redirect_to @customer, notice: t('resources.create.success') if @customer.save
    render :new
  end

  def edit
  end

  def update
    return redirect_to @customer, notice: t('resources.update.success') if @customer.update customer_params
    render :edit
  end

  def destroy
    @customer.destroy
    redirect_to customers_path, notice: t('resources.destroy.success')
  end

  private

  def set_customer
    @customer = Customer.find params[:id]
  end

  def customer_params
    params.require(:customer).permit :name, :surname, :company, :ico, :dic, :address, :email, :phone, :note, :country_id,
                                     :recruitment_center_id, :region_id, :customer_status_id,
                                     requests_attributes: [:_destroy, :id, :date, request_categories: []]
  end
end

app/views/customers/_form.html.haml
- countries = Country.all

= bootstrap_nested_form_for @customer, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-8' do |f|
  = f.alert_message t('views.forms.alert_message')

  .row
    .col-md-6
      .box.box-primary
        .box-header.with-border
          %h3.box-title= t 'customer.form.general'
        .box-body
          = f.text_field :name
          = f.text_field :surname
          = f.text_field :company
          = f.text_field :ico
          = f.text_field :dic
          = f.collection_select :customer_status_id, CustomerStatus.all, :id, :name
          = f.collection_select :recruitment_center_id, RecruitmentCenter.all, :id, :name
          = f.collection_select :country_id, countries, :id, :name
          = f.collection_select :region_id, Region.all, :id, :name, {}, data: {countries: countries.map{ |c| [c.id, c.regions.map{|r| {id: r.id, text: r.name}}]}.to_h}
          = f.text_field :address
          = f.email_field :email
          = f.phone_field :phone
          = f.text_area :note

      .box
        .box-header.with-border
          %h3.box-title= t 'customer.form.requests'
        .box-body
          = f.fields_for :requests, label_col: 'col-sm-3', control_col: 'col-sm-8' do |q|
            = render 'customers/request_fields', f: q

          = f.link_to_add t('customer.form.add_request'), :requests, class: 'btn btn-default btn-sm col-sm-offset-5'


      .box.box-success
        .box-body
          .row
            .col-md-6.col-md-offset-3
              = f.submit t('resources.save'), class: 'btn btn-primary btn-block'

app/views/customers/_request_fields.html.haml
= f.link_to_remove t('resources.delete'), class: 'btn btn-danger btn-xs pull-right'
= f.text_field :date, {data: {provider: :datepicker}}
= f.collection_select :request_categories, RequestCategory.all, :id, :name, {}, multiple: true

%hr

app/views/customers/edit.html.haml
- @page_title = t 'customer.edit.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'info-circle',t('resources.show'), @customer, class: 'btn btn-primary btn-sm'
      = icon_link_to 'plus', t('resources.new'), new_customer_path, class: 'btn btn-default btn-sm'
      = icon_link_to 'list', t('resources.list'), customers_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'

app/views/customers/index.html.haml
- @page_title = t 'customer.index.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'plus', t('resources.new'), new_customer_path, class: 'btn btn-primary btn-sm'

  .box-body
    = search_form Customer,{name: {},
                            surname: {},
                            email: {},
                            customer_status_id: {options: search_options(CustomerStatus, :name)},
                            country_id: {options: search_options(Country, :name)},
                            region_id: {options: search_options(Region, :name)},
                            has_unresolved_request: {type: :boolean},
                            contact_date: {from_to: true, type: :date},
                            request_date: {from_to: true, type: :date},
                            offer_date: {from_to: true, type: :date},
                            recruitment_center_id: {options: search_options(RecruitmentCenter, :name)},
                            company: {},
                            ico: {},
                            dic: {}}

    %small.pull-right.text-muted
      = t 'resources.count', count: number_with_delimiter(@customers.total_count)
      \|
      = t 'resources.pages', count: number_with_delimiter(@customers.total_pages)
    = paginate @customers

    %table.table.table-hover.table-sortable
      %thead
        %tr
          %th= t('activerecord.attributes.customer.id')
          %th= t('activerecord.attributes.customer.contact_date')
          %th= t('activerecord.attributes.customer.customer_status_id')
          %th= t('activerecord.attributes.customer.email')
          %th= t('activerecord.attributes.customer.name')
          %th= t('activerecord.attributes.customer.surname')
          %th= t('activerecord.attributes.customer.recruitment_center_id')
          %th= t('activerecord.attributes.customer.country_id')
          %th

      %tbody.rowlink
        - if @customers.total_count == 0
          %tr
            %td{colspan: 8}= t 'resources.no_items'
        - @customers.each do |customer|
          - style = customer&.customer_status&.color&.present? ? "background-color: #{customer.customer_status.color}" : ''
          %tr{style: style}
            %td= customer.id
            %td= customer.contact_date
            %td= customer.customer_status&.name
            %td= customer.email
            %td= customer.name
            %td= customer.surname
            %td= customer.recruitment_center&.name
            %td= customer.country&.name
            %td= customer.company

            %td.rowlink-skip.text-right
              = icon_link_to 'info-circle', t('resources.show'), customer, class: 'btn btn-primary btn-xs'
              = icon_link_to 'edit', t('resources.edit'), edit_customer_path(customer), class: 'btn btn-default btn-xs'
              = icon_link_to 'times', t('resources.delete'), customer, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'

    %br

app/views/customers/new.html.haml
- @page_title = t 'user.new.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'list', t('resources.list'), users_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'

app/views/customers/show.html.haml
- @page_title = t 'customer.show.title', name: @customer.name, surname: @customer.surname

.row
  .col-md-6
    .box.box-primary
      .box-header.with-border
        %h3.box-title= t 'customer.form.general'
        .box-tools
          = icon_link_to 'edit', t('resources.edit'), edit_customer_path(id: @customer.id), class: 'btn btn-primary btn-sm'
          = icon_link_to 'plus', t('resources.new'), new_customer_path, class: 'btn btn-default btn-sm'
          = icon_link_to 'list', t('resources.list'), customers_path, class: 'btn btn-default btn-sm'

      .box-body
        %dl.dl-horizontal.dl-details
          %dt= t 'activerecord.attributes.customer.customer_status_id'
          %dd= @customer.customer_status&.name

          %dt= t 'activerecord.attributes.customer.email'
          %dd= @customer.email

          %dt= t 'activerecord.attributes.customer.name'
          %dd= @customer.name

          %dt= t 'activerecord.attributes.customer.surname'
          %dd= @customer.surname

          - unless @customer.company.blank?
            %dt= t 'activerecord.attributes.customer.company'
            %dd= @customer.company

            %dt= t 'activerecord.attributes.customer.ico'
            %dd= @customer.ico

            %dt= t 'activerecord.attributes.customer.dic'
            %dd= @customer.dic

          %dt= t 'activerecord.attributes.customer.recruitment_center_id'
          %dd= @customer.recruitment_center&.name

          %dt= t 'activerecord.attributes.customer.country_id'
          %dd= @customer.country&.name

          %dt= t 'activerecord.attributes.customer.region_id'
          %dd= @customer.region&.name

          %dt= t 'activerecord.attributes.customer.address'
          %dd= @customer.address

          %dt= t 'activerecord.attributes.customer.phone'
          %dd= @customer.phone

          %dt= t 'activerecord.attributes.customer.note'
          %dd= @customer.note

  .col-md-6
    .box
      .box-header.with-border
        %h3.box-title= t 'customer.show.requests_offers'
        .box-tools
          = icon_link_to 'plus', t('resources.new'), new_request_path(id: @customer.id), class: 'btn btn-default btn-sm'

      - @customer.requests.each do |request|
        .box-body
          %dl.dl-horizontal.dl-details
            %dt= t 'activerecord.attributes.request.date'
            %dd
              .row
                .col-sm-9
                  = request.date
                .col-sm-3
                  = icon_link_to 'edit', '', edit_request_path(id: request.id), class: 'btn btn-primary btn-xs'
                  = icon_link_to 'times', '', request, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'

            %dt= t 'activerecord.attributes.request.request_categories'
            %dd
              - request.categories.each do |c|
                %span.label.label-success=  c.name

          %dl.dl-horizontal.dl-details
            - offer = request.offer

            - if offer.nil?
              %dt= t 'offer.form.create'
              %dd= icon_link_to 'plus', t('resources.new'), new_offer_path(id: request.id), class: 'btn btn-primary btn-xs'
            - else
              %dt= t 'activerecord.attributes.offer.date'
              %dd
                .row
                  .col-sm-9
                    = offer.date
                  .col-sm-3
                    = icon_link_to 'edit', '', edit_offer_path(id: offer.id), class: 'btn btn-primary btn-xs'
                    = icon_link_to 'times', '', offer, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'
              %dt= t 'activerecord.attributes.offer.contact_date'
              %dd= offer.contact_date
              %dt= t 'activerecord.attributes.offer.internal_id'
              %dd= offer.internal_id

          - unless offer.nil?
            %table.table.table-condensed.table-bordered.table-hover
              %thead
                %th= t 'activerecord.attributes.offer_file.original_filename'
                %th
              %tbody
                - offer.offer_files.each do |file|
                  %tr
                    %td
                      = link_to file.public_name, file.stored_filename.url, target: '_blank'
                    %td.rowlink-skip.text-right
                      = icon_link_to 'times', t('resources.delete'), file, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'
        %hr