config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}

  root 'dashboard#home'

  resources :customers
  resources :users
  resources :emails, except: [:edit, :update, :destroy]
  resources :offers, except: [:index, :show]
  resources :offer_files, only: :destroy
  resources :recruitment_centers, except: :show
  resources :countries, except: :show
  resources :regions, except: :show
  resources :request_categories, except: :show
  resources :requests, except: [:show, :index]
  resources :customer_statuses, except: :show
end

app/models/region.rb
class Region < ApplicationRecord
  include Filterable

  belongs_to :country
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_region, only: [:edit, :update, :destroy]

  def index
    @regions = Region.includes(:country).filter_by(params[:filter]).page(params[:page])
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new region_params
    return redirect_to regions_path, notice: t('resources.create.success') if @region.save
    render :new
  end

  def edit
  end

  def update
    success = @region.update_attributes region_params
    return redirect_to regions_path, notice: t('resources.update.success') if success
    render :edit
  end

  def destroy
    @region.destroy
    redirect_to regions_path, notice: t('resources.destroy.success')
  end

  private

  def set_region
    @region = Region.find params[:id]
  end

  def region_params
    params.require(:region).permit :name, :country_id
  end
end

app/views/regions/_form.html.haml
= bootstrap_nested_form_for @region, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-5' do |f|
  = f.alert_message t 'views.forms.alert_message'

  = f.text_field :name
  = f.collection_select :country_id, Country.all, :id, :name

  = f.form_group do
    = f.submit t('resources.save'), class: 'btn btn-primary'

app/views/regions/edit.html.haml
- @page_title = t 'region.edit.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'plus', t('resources.new'), new_region_path, class: 'btn btn-default btn-sm'
      = icon_link_to 'list', t('resources.list'), regions_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'

app/views/regions/index.html.haml
- @page_title = t 'region.index.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'plus', t('resources.new'), new_region_path, class: 'btn btn-primary btn-sm'

  .box-body
    = search_form Region, {name: {}, country_id: {options: search_options(Country, :name)}}

    %small.pull-right.text-muted
      = t 'resources.count', count: number_with_delimiter(@regions.total_count)
      \|
      = t 'resources.pages', count: number_with_delimiter(@regions.total_pages)
    = paginate @regions

    %table.table.table-hover.table-sortable
      %thead
        %tr
          %th= t('activerecord.attributes.customer.name')
          %th

      %tbody.rowlink
        - if @regions.total_count == 0
          %tr
            %td{colspan: 3}= t 'resources.no_items'
        - @regions.each do |region|
          %tr
            %td= region.name
            %td= region.country.name

            %td.rowlink-skip.text-right
              = icon_link_to 'edit', t('resources.edit'), edit_region_path(region), class: 'btn btn-default btn-xs'
              = icon_link_to 'times', t('resources.delete'), region, :method => :delete, :data => { :confirm => t('resources.confirm_deletion') }, class: 'btn btn-danger btn-xs'

    %br

app/views/regions/new.html.haml
- @page_title = t 'country.new.title'

.box
  .box-header.with-border
    %h3.box-title
    .box-tools
      = icon_link_to 'list', t('resources.list'), countries_path, class: 'btn btn-default btn-sm'

  .box-body
    = render 'form'